### PR TITLE
[1.21] Update Minecraft wiki links

### PR DESCRIPTION
**Pull request by Spongecade**
The Minecraft Fandom wiki has been forked to a new domain: minecraft.wiki. Learn more here: https://minecraft.wiki/w/Minecraft_Wiki:Moving_from_Fandom. This PR updates all URLs accordingly.

If this gets merged, should I create pr's for the older wikis too?

### CODE REVIEW

**Comment by Caltinor** [comment]
Thank you for catching that.

**Comment by Spongecade** [comment]
Should I create pr's for the older wiki versions?

**Comment by Caltinor** [comment]
if it's not too much to ask.  I'd appreciate it.

**Comment by Spongecade** [comment]
I'm on it!

**Pull request merged**
